/// Flutter icons Pets
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Patients
///      fonts:
///       - asset: fonts/Patients.ttf
///
///
///
import 'package:flutter/widgets.dart';
//Icons made by "https://www.flaticon.com/authors/freepik"

class Patients {
  Patients._();

  static const _kFontFam = 'Patients';

  static const IconData diabetic =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hi_bp = const IconData(0xe801, fontFamily: _kFontFam);
}
